export { default as CreatePage } from './CreatePage'
export { default as DeletePage } from './DeletePage'
export { default as UpdatePage } from './UpdatePage'
export { default as GetAllPages } from './GetAllPages'
export { default as GetPageById } from './GetPageById'
